### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by Jaswir** [Rukiri/ZenRPG#1]
Hi, thanks for making this open source game maker game. Glad to see I wasn't the only one to think of such a cool idea as to make an open source game with game maker 💃 
I ran the game, but don't understand what to do, please help!
It seems like you can move the camera with arrow keys. 
And I see this: 
![screen](https://user-images.githubusercontent.com/15957528/59967904-99560b80-9531-11e9-8ba1-81db271a1396.PNG)

**Comment by Chronos-89** [comment]
Everything right now is super technical.
And just updated the GMS2 branch (please pull from this branch as Master will change to Unity soon)  

What you see is a green square this is our test player, and top right
![EhK1Z89](https://user-images.githubusercontent.com/1763264/59978020-9bee4a80-959d-11e9-8e59-394992808034.png)

So what do we see here?
We see our Active Party (I'll commit this so you can see it, it will be in GMS2 branch), we see our party has members Tiffany, Zack, and Harold.   
They were called in our Party Object (Think of this as our Systems tab in RPG Maker, this is where you can set your starting party) 

Our Create Event looks like this right now.
```
RPG_Party_Database_Ini();

RPG_Party_Create_Actor("Harold");
RPG_Party_Create_Actor("Zack");
RPG_Party_Create_Actor("Tiffany");
RPG_Party_Create_Actor("Zod");

RPG_Party_Member_Add(2)
RPG_Party_Member_Add(1)
RPG_Party_Member_Add(0)

And we printed our current party in our draw event.
// Test Draw Active Party
var map, i
for (i=0; i<RPG_Party_Member_Count(); i++) {
    map = ds_list_find_value(party,i);
    draw_text(6,48, "- Active Party -");
    draw_text(6 ,64 +(i * 16), "Actor Name " + ds_map_find_value(map,Actor.Name) + " " + "Menu Slot" + " " + string(i));
}
```

So we used a for loop to draw each party member so we didn't have to create 3 different map variables, write ds_list_find_value 3 times etc and type 0, 1, 2 in the position argument for that command.

Right now this is pretty much a database, we can create, we can add, I'll add remove commands (for party members), I'll add a swap command so you can a "Formation" menu item which is useful if you want to swap Tiffany with Harold's Menu Slot position which than makes Tiffany the leader in the party.

This is a snippet I'll be working on today, to print out the leader of the party. 

Once this gets further there will be an affinity publisher file committed for documentation.
